# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='Pictures/default.png', null=True, upload_to='Pictures'),
        ),
    ]
