# Generated by Django 2.1.5 on 2019-02-26 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='qty',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
