# Generated by Django 2.1.4 on 2019-02-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='hcr_number',
            field=models.IntegerField(),
        ),
    ]
