# Generated by Django 2.1.4 on 2019-02-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyer', '0002_auto_20190208_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='year_admitted',
            field=models.DateTimeField(),
        ),
    ]
