# Generated by Django 2.1.5 on 2019-02-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyer', '0002_lawyer_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyer',
            old_name='qty',
            new_name='rating',
        ),
    ]
