# Generated by Django 2.1.5 on 2019-02-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyer', '0003_auto_20190226_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyer',
            old_name='rating',
            new_name='rate',
        ),
    ]
