# Generated by Django 2.1.5 on 2019-03-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyer', '0004_auto_20190227_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='image',
            field=models.ImageField(null=True, upload_to='Pictures'),
        ),
    ]
