# Generated by Django 2.1.5 on 2019-03-09 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_auto_20190227_0628'),
        ('Lawyer', '0006_lawyer_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='file',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='about',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='contact',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='fields',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Category.Category'),
        ),
    ]
