# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-04 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyer', '0008_remove_lawyer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='freeConsultation',
            field=models.BooleanField(default=False),
        ),
    ]
