# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyer', '0008_remove_lawyer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='image',
            field=models.ImageField(default='Pictures/default.png', null=True, upload_to='Pictures'),
        ),
    ]
