# Generated by Django 2.1.5 on 2019-03-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reply', '0002_auto_20190304_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest', to='Question.Question'),
        ),
    ]
