# Generated by Django 2.1.5 on 2019-02-27 07:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Lawyer', '0004_auto_20190227_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Client.Client')),
                ('lawyerid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Lawyer.Lawyer')),
            ],
        ),
    ]
