# Generated by Django 2.1.5 on 2019-02-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyer', '0004_auto_20190227_0704'),
        ('Client', '0001_initial'),
        ('Rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('lawyerid', 'clientid')},
        ),
    ]
