# Generated by Django 2.0 on 2019-03-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rating', '0002_auto_20190227_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='isHired',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='isRecomended',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
