# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AttorneyEndrosement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorneyendrosement',
            name='fromLawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fromU', to='Lawyer.Lawyer'),
        ),
        migrations.AlterField(
            model_name='attorneyendrosement',
            name='toLawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='toU', to='Lawyer.Lawyer'),
        ),
    ]
