# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttorneyEndrosement', '0002_auto_20190507_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorneyendrosement',
            name='email',
        ),
        migrations.RemoveField(
            model_name='attorneyendrosement',
            name='isHired',
        ),
    ]
