# Generated by Django 2.1.5 on 2019-03-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lawyer', '0008_remove_lawyer_fields'),
        ('Category', '0002_auto_20190227_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Category.Category')),
                ('lawyerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lawyer.Lawyer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lawyercategory',
            unique_together={('lawyerid', 'categoryid')},
        ),
    ]
